In [3]:
import numpy as np

a_list = [1,2,3]
arr1 = np.array(a_list)
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
print(a_list)
print(type(a_list))

[1, 2, 3]
<class 'list'>


In [7]:
import numpy as np

b_list = [[1,2,3],[4,5,6]]
arr2 = np.array(b_list)
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
[np.arange(9)]

[array([0, 1, 2, 3, 4, 5, 6, 7, 8])]

In [10]:
import numpy as np

c_list = np.array([np.arange(9)] * 6)
print(c_list)



[[0 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]


In [1]:
import numpy as np
arr1 = np.zeros(6)
print(arr1)

arr2 = np.zeros((2,4))
print(arr2)

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
print(arr2.shape)
print(arr2.dtype)

(2, 4)
float64
