# Numpy数组的运算

## 1. 加法运算

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a + 1)
print(a - 2)
print(a * 3)
print(a / 2)

[[2 3 4]
 [5 6 7]]
[[-1  0  1]
 [ 2  3  4]]
[[ 3  6  9]
 [12 15 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
